; T-Echo Plus - New version with BHI260AP IMU and additional features
[env:t-echo-plus]
extends = nrf52840_base
board = t-echo-plus
board_level = pr
board_check = true
debug_tool = jlink

# add -DCFG_SYSVIEW if you want to use the Segger systemview tool for OS profiling.
build_flags = ${nrf52840_base.build_flags}
  -Ivariants/nrf52840/t-echo-plus
  -DTTGO_T_ECHO_PLUS                   ; Define board type (needed by SerialModule)
  -DEINK_DISPLAY_MODEL=GxEPD2_154_D67
  -DEINK_WIDTH=200
  -DEINK_HEIGHT=200
  -DUSE_EINK
  -DUSE_EINK_DYNAMICDISPLAY            ; Enable Dynamic EInk
  -DEINK_LIMIT_FASTREFRESH=20          ; How many consecutive fast-refreshes are permitted
  -DEINK_BACKGROUND_USES_FAST          ; (Optional) Use FAST refresh for both BACKGROUND and RESPONSIVE, until a limit is reached.
  -DMESHTASTIC_EXCLUDE_SERIAL=1        ; T-Echo Plus doesn't have Serial2
  -DUSE_SIMPLE_COMPASS_RENDERER=1      ; Use simple 2D compass to save flash space
  -DHAS_BHI260AP                       ; BHI260AP IMU sensor
  -DMESHTASTIC_EXCLUDE_ATAK=1          ; Exclude ATAK support to save space
  -DBHY2_USE_MINIMAL                   ; Exclude BLE/ESLOV features from Arduino_BHY2

build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/t-echo-plus> -<graphics/draw/CompassRenderer.cpp> +<graphics/draw/CompassRendererSimple.cpp>
lib_deps = 
  ${nrf52840_base.lib_deps}
  https://github.com/meshtastic/GxEPD2/archive/55f618961db45a23eff0233546430f1e5a80f63a.zip
  lewisxhe/PCF8563_Library@^1.0.1
  adafruit/Adafruit DRV2605 Library@^1.2.4
;upload_protocol = fs

[env:t-echo-plus-inkhud]
extends = nrf52840_base, inkhud
board = t-echo-plus
board_level = pr
board_check = true
debug_tool = jlink
build_flags = 
  ${nrf52840_base.build_flags}
  ${inkhud.build_flags}
  -I variants/nrf52840/t-echo-plus
  -DMESHTASTIC_EXCLUDE_SERIAL=1        ; T-Echo Plus doesn't have Serial2
build_src_filter = 
  ${nrf52_base.build_src_filter} 
  ${inkhud.build_src_filter}
  +<../variants/nrf52840/t-echo-plus>
lib_deps = 
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${nrf52840_base.lib_deps}
  lewisxhe/PCF8563_Library@^1.0.1
